export const planList = [
    {
        key: "free_b2c",
        title: "Free B2C",
        button: "Registration",
        items: [
            "Profile Page",
            "See the Radio",
            "Mornitoring Results of the weeks",
            "Top 10 songs",
            "Discover similar tracks",
            "Create Playlists of your favorite tracks",
            "Free access to CuRadio for 2 weeks",
        ],
    },
    {
        key:"paid_b2c",
        title: "Paid B2C",
        button: "3$/month",
        items: [
            "Profile Page",
            "See the Radio",
            "Mornitoring Results of the weeks",
            "Top 10 songs",
            "Discover similar tracks",
            "Create Playlists of your favorite tracks",
            "Free access to CuRadio",
        ],
    },
    {
        key:"basic_b2b",
        title: "B2B Basic",
        button: "9.99$/month",
        items: [
            "Profile Page",
            "FP@MW own content",
            "Radio Mornitoring results 10 songs",
            "Monthy change of songs to be mon",
            "Weekly reports",
            "Discover similar tracks to own content",
            "Create Playlists from content",
            "Professional accounting",
        ],
    },
    {
        key:"medium_b2b",
        title: "B2B Medium",
        button: "15.99$/month",
        items: [
            "Profile Page",
            "FP@MW own content",
            "Radio Mornitoring results 10 songs",
            "Monthy change of songs to be mon",
            "Real time reports",
            "Discover similar tracks to own content",
            "Create Playlists from content",
            "Professional accounting",
            "Shop",
            "Ticketing Service",
        ],
    },
    {
        key:"premium_b2b",
        title: "B2B Premium",
        button: "9.99$/month",
        items: [
            "Profile Page",
            "FP@MW own content",
            "Radio Mornitoring results 10 songs",
            "Weekly change of songs to be mon",
            "Real time reports",
            "Radio promo contracts",
            "RM + revenues",
            "Digital description",
            "YT Ads on 3rd party sites",
            "Accounting with chartmetrics",
            "Shop",
            "Blockchain",
            "NFTs",
            "Ticketing Service",
        ],
    },
];